@SERVER_URL = http://localhost:8080
@ACCESS_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZWVjN2I2MDU5MDNkOTRmMDc3OTdhZSIsImlhdCI6MTcxMzUwOTE1MywiZXhwIjoxNzEzNTk1NTUzfQ.tXIdL67BSpHSaDgfK89P3OGhfwlpmhTgU2kRQ-uf7a4

@ROOM_ID =6621dc60fd6facdd5522307d

@BUSINESS_ID=65effd002d3c6a72235bbe8e

####
PUT {{SERVER_URL}}/api/help-desk/create-or-edit-business
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "domains": ["https://test-ttalk.onrender.com", "http://localhost:3001"],
  "color": "red",
  "language": "vis",
  "firstMessage": "Xin chào",
  "firstMessageEnglish": "Hi, how can I help you?",
  "chatFlow": {
    "content": "Root Node111",
    "contentEnglish":"Hello",
    "type": "button",
    "media":[],
    "childrens": [
      {
        "content": "Child Node 12",
        "type": "message",
        "childrens": [
        {
          "content": "Grandchild Node 13",
          "type": "link",
          "childrens": [],
          "media":[]
        },
        {
          "id": 5,
          "content": "Grandchild Node 2",
          "contentEnglish":"test",
          "type": "button",
          "childrens": []
        }
      ]
      }
    ]
  },
  "spaceId":"661df29b8ef8108600f0f9c5"
}

###
POST  {{SERVER_URL}}/api/help-desk/create-client
Content-Type: application/json

{ 
  "members":[]
}

###
GET {{SERVER_URL}}/api/help-desk/spaces/6622111da182f6d2fb794758
Authorization: Bearer {{ACCESS_TOKEN}}


###
GET {{SERVER_URL}}/api/help-desk/business/660ce2a734af0a4726d05497



###
POST {{SERVER_URL}}/api/rooms/create-help-desk-room
Content-Type: application/json

{
  "participants": ["65e554877e9c3e8dc0498323","65e56cfb9cd38aca6cd26d3c"],
  "businessId":"65ee74502d3c6a722301f9e7",
  "senderId":"65e554877e9c3e8dc0498323"
}



####
POST {{SERVER_URL}}/api/messages/help-desk
Content-Type: application/json

{
"clientTempId": "2024-03-12T03:30:36.257Z",
"content": "Xin chào Tech Talk111",
"contentEnglish":"Hello Tech talk",
"language":"en",
"roomId":"65f79b0801513a8725777897",
"userId":"65eec7b605903d94f07797ae",
"senderType":"bot",
"type":"flow-actions",
"actions": [
   {
                "id": "1",
                "data": {
                    "label": "Start conversation",
                    "content":111
                  
                },
        
                "className": "light",
                "type": "root",
                "width": 64,
                "height": 64
            }
]
}


//Business
###
POST {{SERVER_URL}}/api/messages
Authorization: Bearer {{ACCESS_TOKEN}} 
Content-Type: application/json

{
"clientTempId": "2024-03-12T03:30:36.257Z",
"content": "Đây là trang website giúp mình học tiếng Anh",
"contentEnglish":"This is a website help you learn English",
"language":"en",
"roomId":"65efd52b102918180ed719cf"
}

###
DELETE  {{SERVER_URL}}/api/help-desk/65eec80a2d3c6a722349d697
Authorization: Bearer {{ACCESS_TOKEN}} 

###
GET  {{SERVER_URL}}/api/rooms/anonymous/{{ROOM_ID}}?userId=6621dc5dfd6facdd55223077

###
GET {{SERVER_URL}}/api/rooms/anonymous/{{ROOM_ID}}/message?userId=6621dc5dfd6facdd55223077&limit=16


####
GET {{SERVER_URL}}/api/rooms?type=help-desk&spaceId=661dd18f79fa16e0ac8777db
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZWVjN2I2MDU5MDNkOTRmMDc3OTdhZSIsImlhdCI6MTcxMzMyMTQ3OCwiZXhwIjoxNzEzNDA3ODc4fQ.mCYDcDk_p73VPMhSzYFE06xUDbsnFVuAUPukwD0FuPM

###
GET {{SERVER_URL}}/api/rooms?type=help-desk
Authorization: Bearer {{ACCESS_TOKEN}}


###
POST {{SERVER_URL}}/api/help-desk/rating
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "businessId": "65effd002d3c6a72235bbe8e",
  "userId": "65f261b54abba3c51f9a5151",
  "star": 3
}

### 
GET {{SERVER_URL}}/api/search/inboxes?q=h&type=help-desk&spaceId=661dd18f79fa16e0ac8777db
Authorization: Bearer {{ACCESS_TOKEN}}


####
PUT  {{SERVER_URL}}/api/rooms/{{ROOM_ID}}/change-status-room
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  //status: deleted|archived|completed
  "status": "completed"
}


###
GET {{SERVER_URL}}/api/rooms?type=help-desk&status=archived
Authorization: Bearer {{ACCESS_TOKEN}}


###
GET {{SERVER_URL}}/api/help-desk/my-clients?q=&spaceId=661f8dd6d4c0e47632353cef
Authorization: Bearer {{ACCESS_TOKEN}}


###
GET {{SERVER_URL}}/api/help-desk/analytics?type=last-week

###
PATCH  {{SERVER_URL}}/api/help-desk/edit-client-profile
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
"phoneNumber":"035295211",
"userId":"65f25e2a4abba3c51f9a50f3"
}

###
GET {{SERVER_URL}}/api/recommendation/chat?type=help-desk&spaceId=661dd18f79fa16e0ac8777db
Authorization: Bearer {{ACCESS_TOKEN}}

###
GET {{SERVER_URL}}/api/rooms/{{ROOM_ID}}
Authorization: Bearer {{ACCESS_TOKEN}}



####
PUT {{SERVER_URL}}/api/help-desk/create-or-edit-space
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "name":"Manchester city2",
  "avatar":"hrkrkr",
  "backgroundImage":"sss",
  "members":[{
    "email":"hoquanglinh2710@gmail.com",
    "role":"admin"
  }]

 
}


//joined-spaces|my-spaces
####
GET {{SERVER_URL}}/api/help-desk/spaces?type=my_spaces
Authorization: Bearer {{ACCESS_TOKEN}}

###
GET {{SERVER_URL}}/api/help-desk/my-invitations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZWVjN2I2MDU5MDNkOTRmMDc3OTdhZSIsImlhdCI6MTcxMzMyMTQ3OCwiZXhwIjoxNzEzNDA3ODc4fQ.mCYDcDk_p73VPMhSzYFE06xUDbsnFVuAUPukwD0FuPM

###

POST {{SERVER_URL}}/api/help-desk/validate-invite
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZWVjN2I2MDU5MDNkOTRmMDc3OTdhZSIsImlhdCI6MTcxMzMyMTQ3OCwiZXhwIjoxNzEzNDA3ODc4fQ.mCYDcDk_p73VPMhSzYFE06xUDbsnFVuAUPukwD0FuPM
Content-Type: application/json

{
  "token":"a9o-fro-js5-i66-8s5-0t0",
  "status":"accept"
}

###
PUT  {{SERVER_URL}}/api/help-desk/invite-member
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "email":"hoqsus@gmail.com",
  "role":"admin",
  "spaceId":""
}

###

POST  {{SERVER_URL}}/api/help-desk/resend-invitation
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "email":"hoquanglinh2710@gmail.com",
  "role":"admin",
  "spaceId":"661dd18f79fa16e0ac8777db"
}

####
DELETE  {{SERVER_URL}}/api/help-desk/remove-member
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "email":"hoquanglinh2710@gmail.com",
  "spaceId":"661dd18f79fa16e0ac8777db"
}


###

PATCH {{SERVER_URL}}/api/help-desk/change-role
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "email":"hoquanglinh2710@gmail.com",
  "spaceId":"661dd18f79fa16e0ac8777db",
  "role":"member"
}


