POST http://localhost:8080/api/phrases
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTUxYzE1ZDg3YTQxMDdkY2ViYTZjNjciLCJlbWFpbCI6ImhvcXVhbmdsaW5oMjcxMEBnbWFpbC5jb20iLCJpYXQiOjE2OTk5MzM5MTMsImV4cCI6MTcwMjUyNTkxM30.3tTebxRxWBrCMXH3M7fOX5QxNbwf7csAirZpwWfIgdA
Content-Type: application/json

{
    "About yourself": [
      "Hello. I'm [name]. I just started today. It’s so nice to meet you!",
      "I'm [Your Age] years old and currently reside in [Your Location].",
      "I have a passion for [Your Interests/Hobbies], which include [Specific Activities].",
      "I graduated from [Your Educational Background] with a degree in [Your Field of Study].",
      "Professionally, I have experience in [Your Work Experience/Industry].",
      "In my free time, I enjoy [Your Other Hobbies/Activities], as they bring me joy and relaxation.",
      "I am a firm believer in [Your Values/Beliefs], and I strive to live by them every day.",
      "I love meeting new people and learning about different cultures, as it broadens my perspective.",
      "One of my goals is to [Your Aspirations/Goals], as I find it fulfilling and meaningful.",
      "I’m excited to be here and look forward to engaging in meaningful conversations and learning from others."
    ],
    "Family & Friends": [
      "Do you have a lot of friends?",
      "Is there anything special about your best friend?",
      "How long have you known your best friend?",
      "What do you think is the best trait of a friendship?",
      "Is it important to keep in contact with our friends when we’re in a relationship?",
      "Have you known each other long?",
      "How often do you see your friends?",
      "Do you prefer to spend time with your family or your friends?"
    ],
    "School": [
      "Financial support is available for some students in my school.",
      "Many senior students of my school often come to school to help current students.",
      "The cafeteria of my school has yummy and healthy food.",
      "Everyone at my school is friendly, and always available to help each other.",
      "All the students at my school feel safe and happy at school.",
      "The school runs smoothly and has helpful staff and highly professional teachers.",
      "In my school, technology is used a lot to help students learn.",
      "Students can also attend events in other places.",
      "The students of my school are encouraged to help the community.",
      "My school’s name is Rama High School."
    ],
    "Work": [
      "I used to take work home, but I don't do it anymore.",
      "The film highlights the stressful and difficult aspects of the teacher's work.",
      "Some firms expect the guards to work twelve hours a day.",
      "What kind of work do you do?",
      "I was out of work at the time.",
      "She'd have enough money to provide for her children until she could find work.",
      "I want to work, I don't want to be on welfare.",
      "He worked as a bricklayer's mate.",
      "I started working in a recording studio.",
      "He works for the U.S. Department of Transport."
    ],
    "Weather": [
      "After waiting all day, the workers were still looking for a break in the weather so they could resume the search.",
      "Generally speaking, the weather was mild last year.",
      "The weather this week has been good on the whole.",
      "We should lay on a second coat of paint for better protection against the weather.",
      "Our departure tomorrow is contingent on fair weather.",
      "The sea ice is highly variable - frozen solid during cold, calm weather and broken up in large areas of open water during storms.",
      "Spring brings mild weather after the cold winter.",
      "The cold weather continued for three weeks.",
      "The cold weather kept us indoors.",
      "The cold weather has turned the leaves red."
    ],
    "Food": [
      "Please, bring a pinch of salt from your mother.",
      "You hardly had anything.",
      "Have your dinner with me.",
      "What will you have?",
      "Hurry up, food has been served.",
      "It is time to take meals and get ready.",
      "Has Ali taken her meals?",
      "Which pickles do you have?",
      "Have you taken your breakfast?",
      "Today, I will dine out only."
    ],
    "Travel": [
      "I wonder what it is like to travel through space.",
      "The day will soon come when we will conquer space and travel to the moon.",
      "When you travel abroad, you start to feel very expansive, and it's easy to overspend in a mood like that.",
      "It is considered impossible to travel back to the past.",
      "I had a chance to travel abroad.",
      "Would you like to travel abroad?",
      "Many young Japanese travel overseas these days.",
      "Air travel is fast; sea travel is, however, restful.",
      "It is a pity that you cannot travel with us.",
      "We can travel through time. And we do at the remarkable rate of one second per second."
    ],
    "Sport": [
      "I'd say football is my favourite sport.",
      "Billy turned on a radio to get the sports news.",
      "He sported a collarless jacket with pleated black panels.",
      "I'd say football is my favourite sport.",
      "Billy turned on a radio to get the sports news.",
      "I'd say football is my favourite sport."
    ]
  
}
