export const STATUS = {
  MEETING_NOT_FOUND: 'MEETING_NOT_FOUND',
  USER_NOT_IN_ROOM: 'USER_NOT_IN_ROOM',
  JOIN_SUCCESS: 'JOIN_SUCCESS',
  MEETING_END: 'MEETING_END',
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  MEETING_STARTED: 'MEETING_STARTED',
  CALL_NOT_FOUND: 'CALL_NOT_FOUND',
};
