export const STATUS = {
  MEEING_NOT_FOUND: 'MEEING_NOT_FOUND',
  USER_NOT_IN_ROOM: 'USER_NOT_IN_ROOM',
  JOIN_SUCCESS: 'JOIN_SUCCESS',
  MEETING_END: 'MEETING_END',
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
};
