export const MESSAGE_RESPONSE = {
  ERROR: 'BACKEND.MESSAGE.ERROR',
  PASSWORD_PATTERN: 'BACKEND.MESSAGE.PASSWORD_PATTERN',
  EMAIL_EXIST: 'BACKEND.MESSAGE.EMAIL_EXIST',
  USERNAME_EXIST: 'BACKEND.MESSAGE.USERNAME_EXIST',
  ACCOUNT_ALREADY_ACTIVE: 'BACKEND.MESSAGE.ACCOUNT_ALREADY_ACTIVE',
  EMAIL_NOT_SIGNUP: 'BACKEND.MESSAGE.EMAIL_NOT_SIGNUP',
  INVALID_PASSWORD: 'BACKEND.MESSAGE.INVALID_PASSWORD',
  NEW_PASSWORD_SAME_OLD_PASSWORD:
    'BACKEND.MESSAGE.NEW_PASSWORD_SAME_OLD_PASSWORD',
  INVALID_TOKEN: 'BACKEND.MESSAGE.INVALID_TOKEN',
};
