@SERVER_URL = http://localhost:8080
@ACCESS_TOKEN = 
@STATION_ID=

POST  {{SERVER_URL}}/api/stations
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "name":"Dev space",
  "avatar":"hrkrkr",
  "backgroundImage":"sss",
  "members":[
    {
      "email":"19521750@gm.uit.edu.vn",
      "role":"admin"
    },
    {
      "email":"linh@dudaji.vn",
      "role":"member"
    }
  ]
}

###
GET {{SERVER_URL}}/api/stations
Authorization: Bearer {{ACCESS_TOKEN}}

###
GET {{SERVER_URL}}/api/stations/{{STATION_ID}}
Authorization: Bearer {{ACCESS_TOKEN}}

###
PATCH  {{SERVER_URL}}/api/stations/{{STATION_ID}}
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "name":"LCD",
  "avatar":"avatar",
  "backgroundImage":"sss",
}


###
DELETE  {{SERVER_URL}}/api/stations/{{STATION_ID}}
Authorization: Bearer {{ACCESS_TOKEN}}


###
DELETE  {{SERVER_URL}}/api/stations/{{STATION_ID}}/members
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "email": "hoquanghao2710@gmail.com"
}

###
DELETE  {{SERVER_URL}}/api/stations/{{STATION_ID}}/members/leave
Authorization: Bearer {{ACCESS_TOKEN}}


###
POST  {{SERVER_URL}}/api/rooms/stations/{{STATION_ID}}
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
   "participants": [
        "65eec7b605903d94f07797ae",
        "65e56cfb9cd38aca6cd26d3c"
    ]
}

###
GET {{SERVER_URL}}/api/rooms?stationId={{STATION_ID}}
Authorization: Bearer {{ACCESS_TOKEN}}


###
POST {{SERVER_URL}}/api/stations/members/validate-invite
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  //status: accept|decline
  "token":"z1e-iau-2hv-aja-d7k-481",
  "status":"accept"
}


###

POST  {{SERVER_URL}}/api/stations/{{STATION_ID}}/members
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "members":[
    {
      "email":"hoquanghao2710@gmail.com"
    },
    {
      "email":"linh@dudaji.vn"
    }
  ]
}

###
PATCH {{SERVER_URL}}/api/stations/members/generate-link
Authorization: Bearer {{ACCESS_TOKEN}}


###
PATCH  {{SERVER_URL}}/api/stations/{{STATION_ID}}/members/invite-link
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
   "verifyUrl":"http://localhost:3000/station-verify?token=z1e-iau-2hv-aja-d7k-481",
   "email":"hoquanglinh2710@gmail.com"
}

###
###

PATCH {{SERVER_URL}}/api/stations/6679380d322b8781778efae9/set-default
Authorization: Bearer {{ACCESS_TOKEN}}


//Call this api to get default station
###
GET {{SERVER_URL}}/api/auth/me
Authorization: Bearer {{ACCESS_TOKEN}}

###
GET {{SERVER_URL}}/api/stations/station-verify/z1e-iau-2hv-aja-d7k-481
Authorization: Bearer {{ACCESS_TOKEN}}

###
GET {{SERVER_URL}}/api/rooms/pin?stationId={{STATION_ID}}
Authorization: Bearer {{ACCESS_TOKEN}}

###
GET {{SERVER_URL}}/api/search/users?q=&stationId={{STATION_ID}}
Authorization: Bearer {{ACCESS_TOKEN}}

###
GET {{SERVER_URL}}/api/recommendation/chat?stationId={{STATION_ID}}
Authorization: Bearer {{ACCESS_TOKEN}}






