@SERVER_URL = http://localhost:8080
@ACCESS_TOKEN = 

@STATION_ID=6662d3336c2bd7cc71563677

POST  {{SERVER_URL}}/api/stations
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "name":"Dev 123",
  "avatar":"hrkrkr",
  "backgroundImage":"sss",
  "members":[
    {
      "email":"19521750@gm.uit.edu.vn",
      "role":"admin"
    },
    {
      "email":"linh@dudaji.vn",
      "role":"member"
    }
  ]
}

###
GET {{SERVER_URL}}/api/stations
Authorization: Bearer {{ACCESS_TOKEN}}

###
GET {{SERVER_URL}}/api/stations/66612953cd1e1f62aeb42587
Authorization: Bearer {{ACCESS_TOKEN}}

###
PATCH  {{SERVER_URL}}/api/stations/66612953cd1e1f62aeb42587
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "name":"LCD",
  "avatar":"avatar",
  "backgroundImage":"sss",
}


###
DELETE  {{SERVER_URL}}/api/stations/66612953cd1e1f62aeb42587
Authorization: Bearer {{ACCESS_TOKEN}}


###
DELETE  {{SERVER_URL}}/api/stations/{{STATION_ID}}/members
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "email": "hoquanghao2710@gmail.com"
}

###
DELETE  {{SERVER_URL}}/api/stations/{{STATION_ID}}/members/leave
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NjdjNzMzYmE2YTFlZjExYTk5OTI4MSIsImlhdCI6MTcxODYwNDY1NywiZXhwIjoxNzE4NjkxMDU3fQ.IwFWjCbGz49_epPKYU4KDBGn1zHQenTV0JkdUQJNWdQ


###
POST  {{SERVER_URL}}/api/rooms/stations/66739c11ee8195dc93d82a56
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
   "participants": [
        "65eec7b605903d94f07797ae",
        "66616c2e223048e94d801234"
    ]
}

###
GET {{SERVER_URL}}/api/rooms?stationId={{STATION_ID}}
Authorization: Bearer {{ACCESS_TOKEN}}


###
POST {{SERVER_URL}}/api/stations/members/validate-invite
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  //status: accept|decline
  "token":"4dv-lut-1lr-73p-ni1-pzp",
  "status":"accept"
}

###

PATCH {{SERVER_URL}}/api/stations/{{STATION_ID}}/set-default
Authorization: Bearer {{ACCESS_TOKEN}}


